import { lazy, Suspense, useState, type ReactNode } from 'react'
import { motion } from 'framer-motion'
import { ArrowDown, ArrowRight, ArrowUpRight, FileClock, Github, LockKeyhole, Menu, Network, Play, ShieldCheck, Sparkles, Twitter, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Brand } from '../components/Brand'
const HeroScene = lazy(() => import('../components/three/Landing3D').then((module) => ({ default: module.Landing3D })))
const PipelineScene = lazy(() => import('../components/three/Landing3D').then((module) => ({ default: module.Pipeline3D })))
const StoryScene = lazy(() => import('../components/three/Landing3D').then((module) => ({ default: module.StoryScene })))

function SceneFallback({ small = false }: { small?: boolean }) { return <div className={`scene-fallback ${small ? 'scene-fallback-small' : ''}`}><div className="fallback-ring" /><div className="fallback-core" /></div> }

const stages = ['Receive', 'Scan', 'Detect', 'Classify', 'Policy', 'Route', 'Generate', 'Gate', 'Verify', 'Trust']

export function Landing() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="landing-page">
    <header className="landing-nav"><Brand /><nav className={`landing-links ${menuOpen ? 'open' : ''}`}><a href="#product" onClick={() => setMenuOpen(false)}>Product</a><a href="#pipeline" onClick={() => setMenuOpen(false)}>Pipeline</a><a href="#principles" onClick={() => setMenuOpen(false)}>Principles</a><a href="#security" onClick={() => setMenuOpen(false)}>Security</a></nav><div className="landing-actions"><button className="nav-help" onClick={() => document.getElementById('assistant-launcher')?.click()}>Need Help</button><Link className="button button-crimson button-small" to="/login">Try Now <ArrowUpRight size={15} /></Link></div><button className="landing-menu" onClick={() => setMenuOpen((value) => !value)} aria-label="Toggle menu">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></header>
    <main>
      <section className="landing-hero" id="product"><div className="hero-grid" /><div className="hero-copy"><motion.div className="eyebrow-pill" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}><span className="pulse-dot" /> Real-time governance for enterprise AI <ArrowRight size={13} /></motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }}>Make every<br /><span>inference</span> accountable.</motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.36 }}>A control plane between your prompts and production. Detect risk, route intelligently, and prove why every model response was allowed.</motion.p><motion.div className="hero-actions" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.47 }}><Link to="/login" className="button button-crimson button-large">Enter the control plane <ArrowUpRight size={17} /></Link><a href="#pipeline" className="button button-ghost button-large"><Play size={15} fill="currentColor" /> See how it works</a></motion.div><div className="hero-proof"><div className="proof-item"><span className="proof-value">10</span><span className="proof-label">governance stages</span></div><div className="proof-line" /><div className="proof-item"><span className="proof-value">&lt; 50ms</span><span className="proof-label">pre-flight latency</span></div><div className="proof-line" /><div className="proof-item"><span className="proof-value">100%</span><span className="proof-label">audit coverage</span></div></div></div><div className="hero-visual"><Suspense fallback={<SceneFallback />}><HeroScene /></Suspense><div className="visual-tag visual-tag-top"><span className="tag-orb crimson" /> policy boundary <b>active</b></div><motion.div className="visual-annotation annotation-left" whileHover={{ scale: 1.05 }}><span>01</span><div><b>Input boundary</b><small>PII + injection scan</small></div></motion.div><motion.div className="visual-annotation annotation-right" whileHover={{ scale: 1.05 }}><span>02</span><div><b>Decision boundary</b><small>Policy fusion engine</small></div></motion.div><motion.div className="visual-annotation annotation-bottom" whileHover={{ scale: 1.05 }}><span>03</span><div><b>Output boundary</b><small>Safe response</small></div></motion.div></div><a className="scroll-cue" href="#story"><span>Scroll to explore</span><ArrowDown size={15} /></a></section>

      <section className="story-section section-shell" id="story"><div className="section-intro"><div className="eyebrow crimson-text">The control plane</div><h2>From raw prompt<br />to <em>proven</em> answer.</h2><p>Most AI stacks observe after the fact. ControlPlane makes governance a first-class runtime layer — before, during, and after every inference.</p></div><div className="story-grid"><div className="story-visual"><Suspense fallback={<SceneFallback small />}><StoryScene /></Suspense><div className="story-orbit orbit-one" /><div className="story-orbit orbit-two" /><div className="story-shield"><ShieldCheck size={40} /></div><motion.div className="story-signal signal-one" whileHover={{ scale: 1.05 }}><span className="signal-dot" /><div><b>Before</b><small>Understand the request</small></div></motion.div><motion.div className="story-signal signal-two" whileHover={{ scale: 1.05 }}><span className="signal-dot amber" /><div><b>During</b><small>Control the generation</small></div></motion.div><motion.div className="story-signal signal-three" whileHover={{ scale: 1.05 }}><span className="signal-dot cyan" /><div><b>After</b><small>Verify and explain</small></div></motion.div></div><div className="story-steps"><div className="story-step active"><span className="step-number">01</span><div><h3>Before · make risk legible</h3><p>PII, injection, complexity, and intent are scanned in parallel. A layered detector cascade assigns the safest plausible use case before a model ever sees the prompt.</p><div className="step-tags"><span>PII redaction</span><span>Use-case detection</span></div></div></div><div className="story-step"><span className="step-number">02</span><div><h3>During · keep the boundary live</h3><p>Every token crosses a buffered streaming safety gate. The route can fall back, pause, or intervene without exposing an unsafe window.</p><div className="step-tags"><span>Buffered gate</span><span>Risk fusion</span></div></div></div><div className="story-step"><span className="step-number">03</span><div><h3>After · earn the trust score</h3><p>Claims are verified honestly against sources — or marked unverifiable. The result is a transparent score and an event stream you can replay.</p><div className="step-tags"><span>Claim verification</span><span>Full audit trail</span></div></div></div></div></div></section>

      <section className="pipeline-section" id="pipeline"><div className="section-shell"><div className="pipeline-heading"><div><div className="eyebrow cyan-text">One event stream, ten stages</div><h2>Governance that moves<br /><em>at inference speed.</em></h2></div><p>One typed event stream powers the live pipeline, audit log, analytics, and replay. No black boxes. No post-hoc guesswork.</p></div><div className="pipeline-showcase"><div className="pipeline-3d-wrap"><Suspense fallback={<SceneFallback small />}><PipelineScene /></Suspense><span className="pipeline-glow" /></div><div className="stage-list">{stages.map((stage, index) => <motion.div className={`landing-stage ${index === 5 ? 'highlight' : ''}`} key={stage} initial={{ opacity: 0, x: 12 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.7 }} transition={{ delay: index * 0.055 }}><span className="landing-stage-number">{String(index + 1).padStart(2, '0')}</span><span className="landing-stage-line" /><strong>{stage}</strong><small>{['Request received', 'PII & secret scan', 'Prompt injection', 'Risk complexity', 'Use case + intent', 'Versioned rules', 'Model selection', 'Buffered safety', 'Source-backed claims', 'Explainable score'][index]}</small></motion.div>)}</div></div></div></section>

      <section className="features-section section-shell" id="principles"><div className="section-intro centered"><div className="eyebrow">Designed for the hard parts</div><h2>Guardrails with<br /><em>good judgment.</em></h2><p>Not every risk is a block. ControlPlane gives teams the calibrated actions, context, and evidence to make better decisions.</p></div><div className="feature-grid"><FeatureCard number="01" icon={<Network size={20} />} title="Use-case aware" text="A cascade maps every request to the strictest plausible context — from customer support to decision support." accent="crimson" /><FeatureCard number="02" icon={<Sparkles size={20} />} title="Risk fusion" text="Overlapping signals compound deliberately. Injection plus privacy is more than the sum of its parts." accent="amber" /><FeatureCard number="03" icon={<ShieldCheck size={20} />} title="Honest verification" text="Source-backed when possible. UNVERIFIABLE when not. Never pretend self-consistency is ground truth." accent="cyan" /><FeatureCard number="04" icon={<FileClockIcon />} title="Replayable by default" text="Every stage is a typed event. Walk the exact decision path without re-running a model." accent="emerald" /></div></section>

      <section className="security-section section-shell" id="security"><div className="security-card"><div className="security-copy"><div className="eyebrow crimson-text">Built for the audit</div><h2>Trust is a<br /><em>calculation.</em></h2><p>Make a defensible statement about every answer. The trust score is a transparent weighted breakdown — not a mysterious confidence number.</p><Link to="/login" className="text-link">Explore the console <ArrowRight size={15} /></Link></div><div className="score-card"><div className="score-top"><span>Trust score</span><span className="score-live"><span className="pulse-dot green" /> live</span></div><div className="score-number">84<span>/100</span></div><div className="score-bar"><span /></div><div className="score-rows"><ScoreRow label="Privacy" value="94%" color="emerald" /><ScoreRow label="Safety" value="98%" color="emerald" /><ScoreRow label="Accuracy" value="72%" color="amber" /><ScoreRow label="Policy fit" value="91%" color="cyan" /></div><div className="score-foot"><LockKeyhole size={13} /> Weighted for Internal Knowledge</div></div></div></section>

      <section className="final-cta section-shell"><div className="cta-glow" /><div className="eyebrow">Your models. Your rules. Your evidence.</div><h2>Put a control plane<br /><em>between prompt and production.</em></h2><p>Start with a local, deterministic demo. Connect a model when you are ready.</p><Link to="/login" className="button button-crimson button-large">Try ControlPlane free <ArrowUpRight size={17} /></Link></section>
    </main>
    <footer className="landing-footer section-shell"><div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}><Brand /><div className="footer-legal">© 2026 ControlPlane.ai</div></div><div className="footer-note">Real-time governance for enterprise AI.</div><div className="footer-links"><a href="https://github.com/HarshitGupta1812/ControlPlane.ai" target="_blank" rel="noreferrer"><Github size={15} /> GitHub</a><a href="https://discord.com" target="_blank" rel="noreferrer"><CircleIcon /> Discord</a><a href="https://twitter.com" target="_blank" rel="noreferrer"><Twitter size={15} /> Twitter</a><span className="footer-divider" /><a href="#product">Product</a><a href="#pipeline">Pipeline</a><a href="#security">Security</a></div></footer>
  </div>
}

function FeatureCard({ number, icon, title, text, accent }: { number: string; icon: ReactNode; title: string; text: string; accent: string }) { return <article className={`feature-card feature-${accent}`}><div className="feature-top"><span>{number}</span><span className="feature-icon">{icon}</span></div><h3>{title}</h3><p>{text}</p><div className="feature-arrow"><ArrowUpRight size={15} /></div></article> }
function ScoreRow({ label, value, color }: { label: string; value: string; color: string }) { return <div className="score-row"><span>{label}</span><div className="score-mini-bar"><i className={color} style={{ width: value }} /></div><b>{value}</b></div> }
function FileClockIcon() { return <span className="file-clock-icon"><FileClock size={20} /></span> }
function CircleIcon() { return <span className="circle-icon">◌</span> }
