import { Activity, Bell, Check, ChevronRight, CircleHelp, Database, Globe2, KeyRound, LockKeyhole, MonitorCog, Network, RefreshCw, Server, Shield, SlidersHorizontal, UserRound } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { Badge, StatusDot } from '../components/Badge'
import { PageHeader, SectionHeader, Toggle } from '../components/Ui'

const settingsTabs = ['Workspace', 'Runtime', 'Notifications', 'Members']

export function Settings() {
  const [tab, setTab] = useState('Workspace')
  const [toggles, setToggles] = useState({ interventions: true, weekly: true, fallback: false })
  return <div className="settings-page"><PageHeader eyebrow="Workspace / Settings" title="Workspace settings" description="Configure the control plane without exposing provider secrets."><Badge tone="safe">Changes saved automatically</Badge></PageHeader><div className="settings-layout"><nav className="settings-nav glass-panel">{settingsTabs.map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item === 'Workspace' ? <SlidersHorizontal size={15} /> : item === 'Runtime' ? <MonitorCog size={15} /> : item === 'Notifications' ? <Bell size={15} /> : <UserRound size={15} />}{item}<ChevronRight size={14} /></button>)}</nav><section className="settings-content">{tab === 'Workspace' && <WorkspaceSettings />}{tab === 'Runtime' && <RuntimeSettings />}{tab === 'Notifications' && <NotificationSettings toggles={toggles} setToggles={setToggles} />}{tab === 'Members' && <MemberSettings />}</section></div></div>
}

function WorkspaceSettings() { return <><section className="settings-card glass-panel"><SectionHeader title="Workspace profile" detail="Shown in your audit exports." /><div className="settings-form"><label>Workspace name<div className="settings-input"><Network size={15} /><input defaultValue="Northstar Labs" /></div></label><label>Workspace slug<div className="settings-input"><Globe2 size={15} /><input defaultValue="northstar-labs" /></div></label><label>Default geography<div className="settings-input"><Globe2 size={15} /><select defaultValue="Global"><option>Global</option><option>United States</option><option>European Union</option></select></div></label><label>Sector<div className="settings-input"><SlidersHorizontal size={15} /><select defaultValue="Enterprise software"><option>Enterprise software</option><option>Financial services</option><option>Healthcare</option></select></div></label></div></section><section className="settings-card glass-panel"><SectionHeader title="Data boundary" detail="How ControlPlane treats stored governance records." /><div className="setting-row"><div className="setting-row-icon"><LockKeyhole size={16} /></div><div><strong>Sanitized event storage</strong><small>Raw prompts and PII redaction maps never persist to logs or event records.</small></div><Badge tone="safe">Enforced</Badge></div><div className="setting-row"><div className="setting-row-icon"><Database size={16} /></div><div><strong>Retention window</strong><small>Governance events, feedback, and rollups are retained for 90 days.</small></div><button className="subtle-button">Manage <ChevronRight size={13} /></button></div></section></> }
function RuntimeSettings() { return <><section className="settings-card glass-panel"><SectionHeader title="Runtime status" detail="Operational details only. Provider keys remain on the API." action="Refresh" icon={<RefreshCw size={14} />} /><div className="runtime-grid"><Runtime name="API gateway" detail="FastAPI · v0.1.0" status="Healthy" icon={<Server size={16} />} /><Runtime name="PostgreSQL" detail="Connection pool 5 / 15" status="Healthy" icon={<Database size={16} />} /><Runtime name="Event stream" detail="SSE · 42ms p95" status="Healthy" icon={<Activity size={16} />} /><Runtime name="Model router" detail="Groq primary · Gemini fallback" status="Mock mode" icon={<MonitorCog size={16} />} mock /></div></section><section className="settings-card glass-panel"><SectionHeader title="Governance defaults" detail="Per-request parameters can override these values." /><div className="setting-row"><div><strong>Default safety strictness</strong><small>Controls the buffered streaming gate threshold.</small></div><select className="inline-select" defaultValue="Medium"><option>Low</option><option>Medium</option><option>High</option></select></div><div className="setting-row"><div><strong>Compounding session risk</strong><small>Risk decays over a 30-minute rolling session window.</small></div><Badge tone="safe">Enabled</Badge></div></section></> }
function NotificationSettings({ toggles, setToggles }: { toggles: { interventions: boolean; weekly: boolean; fallback: boolean }; setToggles: React.Dispatch<React.SetStateAction<{ interventions: boolean; weekly: boolean; fallback: boolean }>> }) { return <section className="settings-card glass-panel"><SectionHeader title="Notifications" detail="Choose what reaches your workspace inbox." /><div className="setting-row"><div className="setting-row-icon"><Shield size={16} /></div><div><strong>Critical interventions</strong><small>Notify when a fused risk blocks or escalates a request.</small></div><Toggle checked={toggles.interventions} onChange={(value) => setToggles((current) => ({ ...current, interventions: value }))} /></div><div className="setting-row"><div className="setting-row-icon"><Activity size={16} /></div><div><strong>Weekly governance digest</strong><small>Monday summary of volume, trust, risk, and spend.</small></div><Toggle checked={toggles.weekly} onChange={(value) => setToggles((current) => ({ ...current, weekly: value }))} /></div><div className="setting-row"><div className="setting-row-icon"><MonitorCog size={16} /></div><div><strong>Model fallback events</strong><small>Notify whenever routing leaves the primary model.</small></div><Toggle checked={toggles.fallback} onChange={(value) => setToggles((current) => ({ ...current, fallback: value }))} /></div></section> }
function MemberSettings() { return <><section className="settings-card glass-panel"><SectionHeader title="Members" detail="2 seats · managed by workspace owners." action="Invite member" icon={<UserRound size={14} />} /><div className="member-row"><span className="user-avatar">MC</span><div><strong>Maya Chen</strong><small>maya@northstar.ai</small></div><Badge tone="info">Owner</Badge><span className="member-last">Active now</span></div><div className="member-row"><span className="user-avatar secondary">JD</span><div><strong>Jordan Davis</strong><small>jordan@northstar.ai</small></div><Badge tone="safe">Reviewer</Badge><span className="member-last">2 days ago</span></div></section><section className="settings-card glass-panel"><SectionHeader title="API access" detail="Programmatic access uses hashed keys and scoped tenants." /><div className="api-key-row"><div className="key-icon"><KeyRound size={17} /></div><div><strong>Production gateway key</strong><small>Created Aug 18, last used 12 minutes ago</small></div><button className="subtle-button">Rotate key <ChevronRight size={13} /></button></div><div className="settings-warning"><CircleHelp size={15} /><span>Keys are only shown once at creation and are never stored in the browser.</span></div></section></> }
function Runtime({ name, detail, status, icon, mock = false }: { name: string; detail: string; status: string; icon: ReactNode; mock?: boolean }) { return <div className="runtime-item"><span className="runtime-icon">{icon}</span><div><strong>{name}</strong><small>{detail}</small></div><Badge tone={mock ? 'info' : 'safe'}>{mock ? 'Mock' : status}</Badge></div> }
